"""Add Users and Multi-tenancy

Revision ID: 5722af84c0f6
Revises: 
Create Date: 2026-01-22 18:26:29.045850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5722af84c0f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('plan_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('shared_with_email', sa.String(), nullable=True),
    sa.Column('permission', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_shares_id'), 'plan_shares', ['id'], unique=False)
    op.add_column('atividades', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'atividades', 'users', ['user_id'], ['id'])
    op.add_column('estrategia', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'estrategia', 'users', ['user_id'], ['id'])
    op.add_column('insights', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'insights', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'insights', type_='foreignkey')
    op.drop_column('insights', 'user_id')
    op.drop_constraint(None, 'estrategia', type_='foreignkey')
    op.drop_column('estrategia', 'user_id')
    op.drop_constraint(None, 'atividades', type_='foreignkey')
    op.drop_column('atividades', 'user_id')
    op.drop_index(op.f('ix_plan_shares_id'), table_name='plan_shares')
    op.drop_table('plan_shares')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
